// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage =
  | { type: "CreateGame" }
  | { type: "JoinRoom"; room_id: string }
  | { type: "StartGame"; room_id: string }
  | { type: "FlipCard"; card_id: number };
