// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "../../app/types/Player";
import type { Card } from "./Card";
import type { GameStatus } from "./GameStatus";

export type GameState = { cards: Array<Card>, players: [Player, Player | null], current_turn: string, scores: [number, number], timer: number, status: GameStatus, winner: string | null, };
